sudo: required
services:
  - docker

before_install:
  - docker build -t aptu71/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aptu71/react-test npm run test 

after_success:
  - docker build -t aptu71/client ./client
  - docker build -t aptu71/worker ./worker
  - docker build -t aptu71/nginx ./nginx
  - docker build -t aptu71/server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push aptu71/client
  - docker push aptu71/worker
  - docker push aptu71/nginx
  - docker push aptu71/server

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-085557256654"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY